title: Enzo Fiorello
email: efiorello@gmail.com
author: Enzo Fiorello
description: <p>One morning, as Gregor Samsa was waking up from anxious dreams, he discovered that in bed he had been changed into a monstrous verminous bug. He lay on his armour-hard back and saw, as he lifted his head up a little, his brown, arched abdomen divided up into rigid bow-like sections.</p>
baseurl: "" 
url: ""
twitter_username: jekyllrb
github_username:  jekyll


# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

collections:
  projects:
    output: true
    permalink: /:collection/:title

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
